const PaymentFormActionTypes = {
  CHOOSE_PHONE: "CHOOSE_PHONE",
  CHOOSE_EMAIL: "CHOOSE_EMAIL",
  CLEAR_CONTACT_PREFERENCE_INFO: "CLEAR_CONTACT_PREFERENCE_INFO",
  OK_BUTTON_CLICKED: "OK_BUTTON_CLICKED",
  CLEAR_OK_BUTTON_CLICKED: "CLEAR_OK_BUTTON_CLICKED",
};

export default PaymentFormActionTypes;
