export const FINAL_ITEM_ACTION_TYPES = {
  ADD_FINAL_ITEM: "ADD_FINAL_ITEM",
  ADD_SIZE_SELECTED_PRICE: "ADD_SIZE_SELECTED_PRICE",
  HAS_SIZE_BEEN_CHOSEN: "HAS_SIZE_BEEN_CHOSEN",
  ADD_GRATED_CHEESE_PRICE: "ADD_GRATED_CHEESE_PRICE",
  ADD_DONER_MEAT_PRICE: "ADD_DONER_MEAT_PRICE",
  ADD_CHEESE_SLICE: "ADD_CHEESE_SLICE",
};
