export const FINAL_ITEM_ACTION_TYPES = {
  ADD_SIZE_SELECTED_PRICE: "ADD_SIZE_SELECTED_PRICE",
  ADD_CHOSEN_SIZE: "ADD_CHOSEN_SIZE",
  ADD_SALT_AND_VINEGAR: "ADD_SALT_AND_VINEGAR",
  ADD_GRATED_CHEESE_PRICE: "ADD_GRATED_CHEESE_PRICE",
  ADD_DONER_MEAT_PRICE: "ADD_DONER_MEAT_PRICE",
  ADD_CHEESE_SLICE: "ADD_CHEESE_SLICE",
  ADD_SALAD: "ADD_SALAD",
  ADD_SAUCES: "ADD_SAUCES",
  ADD_SPECIAL_INSTRUCTIONS: "ADD_SPECIAL_INSTRUCTIONS",
  ADD_QUANTITY: "ADD_QUANTITY",
  CLEAR_FINAL_ITEM: "CLEAR_FINAL_ITEM",
};
