export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "FETCH_PRODUCTS_FAILED",
  ADD_INDIVIDUAL_PRODUCT: "ADD_INDIVIDUAL_PRODUCT",
  CLEAR_INDIVIDUAL_PRODUCT: "CLEAR_INDIVIDUAL_PRODUCT",
  SET_SHOW_HELP_TEXT: "SET_SHOW_HELP_TEXT",
};
