export const CART_ACTION_TYPES = {
  UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
  CHANGE_CART_ITEM_QUANTITY: "CHANGE_CART_ITEM_QUANTITY",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  CHOOSE_CONTACT_METHOD: "CHOOSE_CONTACT_METHOD",
  HANDLE_SHOW_CARD_INPUT: "HANDLE_SHOW_CARD_INPUT",
  SET_CUSTOMER_DETAILS: "SET_CUSTOMER_DETAILS",
  CLEAR_CUSTOMER_DETAILS: "CLEAR_CUSTOMER_DETAILS",
};
