export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: "SET_CART_ITEMS",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  // ADD_TOTAL_PRICE: "ADD_TOTAL_PRICE",
  // RESET_TOTAL_PRICE: "RESET_TOTAL_PRICE",
  // UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
};
