export const CART_ACTION_TYPES = {
  UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
  CHANGE_CART_ITEM_QUANTITY: "CHANGE_CART_ITEM_QUANTITY",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  RESET_TOTAL_PRICE: "RESET_TOTAL_PRICE",
  // ADD_TOTAL_PRICE: "ADD_TOTAL_PRICE",
};
