export const PRODUCTS_DATA = [
  {
    title: "burgers",
    items: [
      {
        id: 1,
        name: "beef burger",
        description: "",
        price: 2.9,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        drinkAvailable: false,
        doublePrice: 0.5,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 2,
        name: "chicken burger",
        description: "",
        price: 3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 1,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 3,
        name: "chicken fillet sandwich",
        description: "",
        price: 3.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 4,
        name: "veggie burger",
        description: "",
        price: 2.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 5,
        name: "halloumi burger",
        description: "",
        price: 2.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 6,
        name: "chicken zinger burger",
        description: "",
        price: 3.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "chicken",
    items: [
      {
        id: 7,
        name: "roast chicken breast",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 8,
        name: "southern fried chicken",
        description: "",
        price: 1.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 3.4,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: true,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 2.3,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 1.2,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 9,
        name: "chicken nuggets",
        description: "",
        price: 2.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0.4,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: true,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 1.2,
        twentyNuggetsPrice: 2,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 10,
        name: "6 chicken wings",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 11,
        name: "6 chicken wings & chips",
        description: "",
        price: 3.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 12,
        name: "southern fried chicken & chips",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: true,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 1.9,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 1.2,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 13,
        name: "southern fried chicken & doner meat",
        description: "",
        price: 4.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: true,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 1.7,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 1.1,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 14,
        name: "golden nugget meal",
        description: "9 nuggets, chips & naan bread",
        price: 4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 15,
        name: "golden fillet sandwich meal",
        description: "chicken fillet burger, chips & can",
        price: 4.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: true,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 16,
        name: "mini feast meal",
        description: "2 pieces of chicken, chips, beans & a can",
        price: 5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: true,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 17,
        name: "bargain box",
        description: "5 pieces of chicken, chips & a can",
        price: 7.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: true,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "chickencurry",
    items: [
      {
        id: 18,
        name: "chicken curry with chips",
        description: "",
        price: 3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.3,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 19,
        name: "chicken curry with rice",
        description: "",
        price: 3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.3,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 20,
        name: "chicken curry with chips & rice",
        description: "",
        price: 4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 21,
        name: "chicken curry with naan bread & chips",
        description: "",
        price: 5.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 22,
        name: "chicken curry with naan bread & rice",
        description: "",
        price: 5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
    ],
  },
  {
    title: "chips",
    items: [
      {
        id: 23,
        name: "cone of chips",
        description: "",
        price: 1.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 24,
        name: "regular chips",
        description: "",
        price: 2.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 25,
        name: "large chips",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 26,
        name: "chips & cheese",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 27,
        name: "cone of chips with sauce",
        description: "",
        price: 1.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: true,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 28,
        name: "tray of chips with 1 condiment",
        description:
          "chips on a tray with an option of gravy / peas / curry / beans",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.4,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 29,
        name: "tray of chips with 2 condiments",
        description:
          "chips on a tray with an option of gravy / peas / curry / beans",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 2,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.5,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 30,
        name: "chips in pitta bread",
        description: "",
        price: 2.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 31,
        name: "potato fritter",
        description: "",
        price: 0.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 32,
        name: "potato wedge",
        description: "",
        price: 0.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 33,
        name: "6 potato wedges",
        description: "",
        price: 2.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 34,
        name: "french fries",
        description: "",
        price: 2.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 35,
        name: "chips in pitta bread & salad",
        description: "",
        price: 4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 36,
        name: "chips in naan bread & salad",
        description: "",
        price: 5.4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 37,
        name: "chip bap",
        description: "",
        price: 2.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "drinks",
    items: [
      {
        id: 38,
        name: "cans ( drinks )",
        description: "",
        price: 1.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: true,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 40,
        name: "bottles ( drinks )",
        description: "",
        price: 2.1,
        anyPieAvailable: false,
        bottlesAvailable: true,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "extras",
    items: [
      {
        id: 42,
        name: "gravy",
        description: "",
        price: 1.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 43,
        name: "mushy peas",
        description: "",
        price: 1.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 44,
        name: "curry sauce",
        description: "",
        price: 1.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 45,
        name: "baked beans",
        description: "",
        price: 1.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 46,
        name: "tub of sauce",
        description: "",
        price: 0.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.7,
        mediumPrice: 0.5,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 47,
        name: "tub of chicken curry",
        description: "",
        price: 1.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 48,
        name: "bottle of vinegar",
        description: "",
        price: 1.4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 49,
        name: "bottle of ketchup",
        description: "",
        price: 1.4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 50,
        name: "tub of grated cheese",
        description: "",
        price: 1.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 51,
        name: "pickled onion",
        description: "",
        price: 0.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 52,
        name: "pickled egg",
        description: "",
        price: 0.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 53,
        name: "toasted pitta bread",
        description: "",
        price: 0.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 54,
        name: "toasted naan bread",
        description: "",
        price: 1.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 55,
        name: "bap with butter",
        description: "",
        price: 0.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
    ],
  },
  {
    title: "fish",
    items: [
      {
        id: 56,
        name: "battered cod fish",
        description: "",
        price: 3.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 2.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
      },
      {
        id: 57,
        name: "battered haddock fish",
        description: "",
        price: 3.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 2.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 58,
        name: "breadcrumb cod fish",
        description: "",
        price: 3.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 2.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 59,
        name: "breadcrumb haddock fish",
        description: "",
        price: 3.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 2.2,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 60,
        name: "10 pieces of scampi",
        description: "",
        price: 3.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 61,
        name: "fishcake",
        description: "",
        price: 1.65,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 62,
        name: "tinned roe",
        description: "",
        price: 1.45,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "jacketpotato",
    items: [
      {
        id: 63,
        name: "jacket potato with butter & cheese",
        description: "",
        price: 2.5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 64,
        name: "jacket potato with butter, cheese & beans",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
    ],
  },
  {
    title: "kebabs",
    items: [
      {
        id: 65,
        name: "doner kebab",
        description: "",
        price: 3.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: true,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 66,
        name: "chicken kebab",
        description: "tikka or mediterranean",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        chickenKebabTypeAvailable: true,
        donerKebabTypeAvailable: false,
        mixedKebabTypeAvailable: false,
        meatsAvailable: 1,
        noOptionsAvailable: false,
      },
      {
        id: 67,
        name: "mixed meats ( 2 meats ) kebab",
        description: "choice of doner, tikka or mediterranean",
        price: 3.4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: true,
        meatsAvailable: 2,
        noOptionsAvailable: false,
      },
      {
        id: 68,
        name: "mixed meats ( 3 meats ) kebab",
        description: "doner, tikka & mediterranean",
        price: 3.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: true,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
  {
    title: "pies",
    items: [
      {
        id: 69,
        name: "meat & potato pie",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 70,
        name: "steak & kidney pie",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 71,
        name: "all steak pie",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 72,
        name: "chicken & mushroom pie",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 73,
        name: "cheese & onion pie",
        description: "",
        price: 2.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 74,
        name: "all steak pudding",
        description: "",
        price: 2.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 75,
        name: "steak & kidney pudding",
        description: "",
        price: 2.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
    ],
  },
  {
    title: "savouries",
    items: [
      {
        id: 76,
        name: "sausage",
        description: "",
        price: 1.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.45,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 77,
        name: "battered sausage",
        description: "",
        price: 1.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: true,
        largePrice: 0.45,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: true,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 78,
        name: "saveloy sausage",
        description: "",
        price: 1.65,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 79,
        name: "sausage bap",
        description: "",
        price: 2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 80,
        name: "veggie spring roll",
        description: "",
        price: 2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 81,
        name: "12 onion rings",
        description: "",
        price: 2.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 82,
        name: "mushy pea fritter",
        description: "",
        price: 1.4,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 83,
        name: "plain burger",
        description: "",
        price: 1.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 84,
        name: "battered burger",
        description: "",
        price: 1.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 85,
        name: "5 halloumi sticks & small sauce",
        description: "",
        price: 5,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 86,
        name: "1 halloumi stick",
        description: "",
        price: 0.85,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
      {
        id: 87,
        name: "battered mushrooms",
        description: "",
        price: 1.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: false,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: true,
      },
    ],
  },
  {
    title: "specials",
    items: [
      {
        id: 88,
        name: "mini fish & chips",
        description: "served with a choice of peas, beans, curry or gravy.",
        price: 4.9,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 89,
        name: "small sausage & chips",
        description: "Served with a choice of peas, beans, curry or gravy.",
        price: 3.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 90,
        name: "small fishcake & chips",
        description: "Served with a choice of peas, beans, curry or gravy.",
        price: 3.2,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 91,
        name: "small sausage, chips & fishcake",
        description: "Served with a choice of peas, beans, curry or gravy.",
        price: 3.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 92,
        name: "any pie & chips",
        description: "Served with a choice of peas, beans, curry or gravy.",
        price: 4.9,
        anyPieAvailable: true,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 94,
        name: "mega snack box",
        description:
          "chips, 5 onion rings, 5 nuggets, 5 wings & any tub of sauce",
        price: 5.8,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 1,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 95,
        name: "single burger & chips",
        description: "",
        price: 3.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 96,
        name: "double burger & chips",
        description: "",
        price: 4.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 97,
        name: "chicken burger & chips",
        description: "",
        price: 4.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 98,
        name: "chicken zinger burger & chips",
        description: "",
        price: 3.9,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 99,
        name: "veggie burger & chips",
        description: "",
        price: 3.6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 100,
        name: "halloumi burger & chips",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: true,
        condimentsAvailable: 0,
        donerMeatAvailable: true,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: true,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 101,
        name: "kids sausage box",
        description: "",
        price: 2.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 102,
        name: "kids 6 nuggets meal",
        description: "",
        price: 3.3,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: false,
        saltAndVinegarAvailable: true,
        saucesAvailable: false,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 103,
        name: "doner kebab meal",
        description:
          "kebab in pitta bread with salad served with a side of chips in tray",
        price: 5.7,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
      {
        id: 104,
        name: "chicken kebab meal",
        description:
          "chicken kebab in a pitta bread with salad served with a side of chips in tray",
        price: 5.9,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 1,
        noOptionsAvailable: false,
      },
      {
        id: 105,
        name: "mixed 2 meat kebab meal",
        description:
          "2 x meats kebab in a pitta bread served with salad with a side of chips in tray",
        price: 6,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 2,
        noOptionsAvailable: false,
      },
      {
        id: 106,
        name: "mixed 3 meat kebab meal",
        description:
          "3 x meats kebab in a pitta bread served with salad with a side of chips in tray",
        price: 6.1,
        anyPieAvailable: false,
        bottlesAvailable: false,
        cheeseSliceAvailable: false,
        condimentsAvailable: 0,
        donerMeatAvailable: false,
        doublePrice: 0,
        drinkAvailable: false,
        fourPiecePrice: 0,
        gratedCheeseAvailable: false,
        hasSizeOption: false,
        largePrice: 0,
        mediumPrice: 0,
        nineNuggetsPrice: 0,
        onePiecePrice: false,
        saladAvailable: true,
        saltAndVinegarAvailable: true,
        saucesAvailable: true,
        coneOfChipsSauce: false,
        sixNuggetsPrice: false,
        smallPrice: false,
        threePiecePrice: 0,
        twelveNuggetsPrice: 0,
        twentyNuggetsPrice: 0,
        twoPiecePrice: 0,
        hasTypeOption: false,
        meatsAvailable: 0,
        noOptionsAvailable: false,
      },
    ],
  },
];
